language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: elizeuborges-github
    token:
      secure: "ec2q0LUJ87cSLmM+QSGixwhzsXEsgnhQ3AYcyD4SydJ6Ohl7jQgLYZTgbkw2falLV8u7RwqJ7PGLVetQy5ymS8zI11upwHwoBpZvnythcYU1Qg5hKGsbzUbl+gYCxAOEO7vGooRbC0xmVBK3d5b8d0q6BbW+hBZL8rOYjm5XfSzZWNDRHgUWRhEIIK7i6/uFfcYca2xvp6l1oW0zXWCUDduLCQmTtl9lJZXWGmkC+EpYrxJd116FdsvvfR426/rJzTeqyb6BWrd31dn1C5+ckt/nbiw7qWA9kKte7W4E+YovZVcSQQVdbz3D8z8kfpTI9xGCWTMWfOAQmFN2OenmUqUgdTLZMI6QPSnbx5fsqlIyuIbwcFxYijVk1u7o6TE2jXfV/8ZGy9+w8lwBkaXfgyTVj4HJ06TuEUchpLQVsxMQStzDCCWcMlXevGTv7TqjOXobKE/dKWAGkwPOVgNovg72O4wN/6FacVo5vLaDw5+QDRsBPBOZa/MZPDRKGi+mSjg0TqvK5LQ4DGcAcYxfxiO0QohI0Z+EBzbt11BAHT2wqPUPd93r+01AA9j1JX0UcdJrh6Q54l6XrgCnQJcFtjg2ZCUSaSZnAvKpIoBmzcK451tz8smVvFjzhqMcIPrsZp6SaANhCboTB/dHf3/LnK/fPBdDL0nroI5PJ2Wj1wE="
jdk:
  - oraclejdk8

script:
  - mvn clean test sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)